name: iban_to_bic
description: Determines the SWIFT BIC of any AT, BE, DE, LT, LU or NL IBAN.
version: 0.0.8
homepage: https://github.com/xonaman/flutter_iban_to_bic

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  iban: ^1.0.1

dev_dependencies:
  flutter_lints: ^3.0.2